site_name: Python, perfectionnement
repo_url: https://github.com/darko-itpro/formation-Python_perfectionnement_bases
plugins:
theme:
  name: material
  features:
    - navigation.indexes
markdown_extensions:
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Home: index.md
  - En français:
    - fr/index.md
    - Documentation des démos:
        - fr/demos/index.md
        - Le parallélisme:
            - Le multithreading: fr/demos/parallelism/threads.md
            - Le multiprocessing: fr/demos/parallelism/processes.md
    - Rappels et aide mémoire:
        - POO Avancée: fr/manual/poo.md
        - Les itérateurs: fr/manual/iterators.md
        - Context Managers: fr/manual/context_managers.md
        - Les décorateurs: fr/manual/decorators.md
    - Exercices:
      - Rappels:
        - fr/activities/rappels_1.md
        - fr/activities/rappels_2.md
        - fr/activities/rappels_3.md
      - Programmation Orientée Objet:
        - fr/activities/iterators.md
        - fr/activities/properties.md
      - Decorators:
        - fr/activities/decorators/closures.md
        - fr/activities/decorators/decorators_1.md
        - fr/activities/decorators/decorators_2.md
        - fr/activities/decorators/decorators_3.md
        - fr/activities/decorators/decorators_4.md
      - Context Managers:
        - fr/activities/context_managers/index.md
        - fr/activities/context_managers/activity_1.md
        - fr/activities/context_managers/activity_2.md
        - fr/activities/context_managers/activity_3.md
  - In English:
    - en/index.md
    - Reference manual:
        - Advanced OOP: en/manual/oop.md
        - Iterators: en/manual/iterators.md
        - Context Managers: en/manual/context_managers.md
        - Decorators: en/manual/decorators.md
    - Activities:
        - Reminders:
          - en/activities/bases/rappels_1.md
          - en/activities/bases/rappels_2.md
          - en/activities/bases/rappels_3.md
        - Object Oriented Programming:
          - en/activities/oop/iterators.md
          - en/activities/oop/properties.md
        - Decorators:
          - en/activities/decorators/index.md
          - en/activities/decorators/closures.md
          - en/activities/decorators/decorators_1.md
          - en/activities/decorators/decorators_2.md
          - en/activities/decorators/decorators_3.md
          - en/activities/decorators/decorators_4.md
        - Context Managers:
          - en/activities/context_managers/index.md
          - en/activities/context_managers/activity_1.md
          - en/activities/context_managers/activity_2.md
          - en/activities/context_managers/activity_3.md
